name: onemoney_sdk
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.1.0
  pin_code_fields: ^7.2.0
  path: ^1.8.0
  shared_preferences: ^2.0.6
  cached_network_image: any
  flutter_spinkit: "^5.0.0"
  percent_indicator: "^3.0.1"
  intl: ^0.17.0
  collection: ^1.15.0
  fluttertoast: ^8.0.7
  connectivity: ^3.0.6
  onemoney:
    path: D:\ONEMONEY_FLUTTER\ONEMONEY_HEADLESS_AWS

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.onemoney.sdk.onemoney_sdk
        pluginClass: OnemoneySdkPlugin
      ios:
        pluginClass: OnemoneySdkPlugin
      web:
        pluginClass: OnemoneySdkWeb
        fileName: onemoney_sdk_web.dart

  uses-material-design: true

  assets:
    - packages/onemoney_sdk/assets/image/one_money_logo.png
    - packages/onemoney_sdk/assets/image/account_created.png
    - packages/onemoney_sdk/assets/image/verify_number.png
    - packages/onemoney_sdk/assets/image/link_account.png
    - packages/onemoney_sdk/assets/image/reuest_person_img.png
    - packages/onemoney_sdk/assets/image/check_mark.png
    - packages/onemoney_sdk/assets/image/saving_account.png
    - packages/onemoney_sdk/assets/image/consent_request.png
    - packages/onemoney_sdk/assets/image/edit.png
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
